// Number Guessing Game project 

// //This guess the number game is a short TypeScript/Node.js project that
// allows the user to guess the number generated by the computer. There are also several ways to alter the game,
//  like adding more rounds or displaying the score. It’s quite simple and uses the random function to generate a number.

console.log ("Guess a number between 50 to 1 ");

//creating variable 

let a :number = Math.floor(Math.random() * 100);

import inquirer from "inquirer"

while (true) {
    let input =await inquirer.prompt
    ({name : "guess" , 
    type :"number",
    message : "Enter your guess number :"})

//code  for generate given number 

let ans :number = input.guess
if (a==ans)

    {console.log ("Congratulations! your guess number is correct .")
        break;

    }
    else {
        console.log ("SORRY TRY AGAIN")
    }

    //ADDING HINT 
    
if (a > ans ){

    console.log ("HINT : Number is higher ")
}
else {
    console.log ("HINT : Number is lower")
}
console.log ("GAME IS OVER !")

}
